# Generated by Django 3.2.9 on 2022-02-17 10:44

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20220209_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='books/covers/%Y/%m/%d'),
        ),
    ]
