# Generated by Django 3.2.9 on 2022-02-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'new'), (2, 'hide'), (3, 'published')], default=1),
        ),
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'new'), (2, 'hide'), (3, 'published')], default=1),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='source',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
