# Generated by Django 3.2.9 on 2022-03-09 09:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20220228_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
