# Generated by Django 3.2.9 on 2022-03-10 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_alter_gallery_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Galeria', 'verbose_name_plural': 'Galerie'},
        ),
    ]
